stages:
    - test
    - benchmark

test:
    stage: test
    script: 
        - cd deliverable
        - ./test.sh
    cache:
        key: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
        paths:
            - deliverable
        policy: pull-push
    tags:
        - "fdedi"

benchmark:
    stage: benchmark
    script: 
        - cd deliverable
        - ./build.sh
        - cd ..
        - /data/delivery/measureTaxi ./deliverable/submit.sh
    cache:
        key: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
        paths:
            - deliverable
        policy: pull-push
    tags:
        - "fdedi"

clear_cache_test:
    stage: test
    script:
        - rm -rf ./build/*
    cache:
        key: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
        paths:
            - deliverable
        policy: pull-push
    when: manual
    allow_failure: true

clear_cache_benchmark:
    stage: benchmark
    script:
        - rm -rf ./build/*
    cache:
        key: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
        paths:
            - deliverable
        policy: pull-push
    when: manual
    allow_failure: true
